-- Generated by nwg-displays on 2026-06-12 at 17:24:37. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "0x360",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "2560x1440@144.0",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-1",
    mode = "1920x1080@60.0",
    position = "4480x360",
    scale = 1.0
})
